# Generated by Django 6.0.2 on 2026-02-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_cast_movie_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
